### ISSUE TITLE
Not execute the app

### ISSUE THREAD

**Issue by andygeek** [orionjs/orionjs#106]
When I run `orion start` after creating a new project get the fallowing error.

````
Error: spawn mongod ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn mongod',
  path: 'mongod',
  spawnargs: [
    '--dbpath=.orion/db/data',
    '--port=3001',
    '--logpath',
    '.orion/db/logs/mongolog.log'
  ]
}
````

**Comment by morph3o** [comment]
Hi @andygeek, it happens because you don't have `mongo` installed as a service probably. In case you have mongo somewhere else such as docker, you can define the following env variable:

`export MONGO_URL="mongodb://<server-ip>:<port>/<your-database>`
